// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularHouse.Server.DeviceManagement.Infrastructure.DataAccess.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModularHouse.Server.DeviceManagement.Infrastructure.DataAccess.Database.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20240311112459_Liquided_Users")]
    partial class Liquided_Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.AreaAggregate.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.DeviceAggregate.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.ModuleAggregate.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("RouterId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.RouterAggregate.Router", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Routers");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.ModuleAggregate.Module", b =>
                {
                    b.HasOne("ModularHouse.Server.DeviceManagement.Domain.DeviceAggregate.Device", "Device")
                        .WithOne("Module")
                        .HasForeignKey("ModularHouse.Server.DeviceManagement.Domain.ModuleAggregate.Module", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModularHouse.Server.DeviceManagement.Domain.RouterAggregate.Router", "Router")
                        .WithMany("Modules")
                        .HasForeignKey("RouterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Router");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.RouterAggregate.Router", b =>
                {
                    b.HasOne("ModularHouse.Server.DeviceManagement.Domain.AreaAggregate.Area", "Area")
                        .WithMany("Routers")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModularHouse.Server.DeviceManagement.Domain.DeviceAggregate.Device", "Device")
                        .WithOne("Router")
                        .HasForeignKey("ModularHouse.Server.DeviceManagement.Domain.RouterAggregate.Router", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.AreaAggregate.Area", b =>
                {
                    b.Navigation("Routers");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.DeviceAggregate.Device", b =>
                {
                    b.Navigation("Module");

                    b.Navigation("Router");
                });

            modelBuilder.Entity("ModularHouse.Server.DeviceManagement.Domain.RouterAggregate.Router", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
